# Template for the portal Secret. DO NOT put real values here or commit this file
# with secrets. Copy it to portal-secrets.sops.yaml and encrypt:
#
#   cd deploy
#   cp portal/secrets/portal-secrets.example.yaml \
#      portal/secrets/portal-secrets.sops.yaml
#   # fill in real values, then:
#   sops --encrypt --in-place portal/secrets/portal-secrets.sops.yaml
#
# Generate the values:
#   AUTH_SECRET          : openssl rand -base64 32   (Auth.js session encryption key)
#   AUTH_COGNITO_SECRET  : the portal's Cognito app-client secret (confidential client)
apiVersion: v1
kind: Secret
metadata:
    name: portal-secrets
    namespace: janus-license
    labels:
        app.kubernetes.io/name: portal
type: Opaque
stringData:
    #ENC[AES256_GCM,data:line6XqfkuPN1qGbJR8oPvpelZpJ10dSpkEEfl2FsZJLyUskOTAQ3yLp1s1WFM4nNplfhZmIPKLUsxtDHJ3jgTlpQaq6,iv:0ttpjUxnqab+54XG5ZGfO8mD7GD9q/Pgs9Sfbf+tc0k=,tag:eH3HV+LGzfNLdm0oaD13UA==,type:comment]
    AUTH_SECRET: ENC[AES256_GCM,data:nxttycrwEFnk9Lls2Yj+Ehz36i9zIyBfg/Ds9Obe8asaZ/EYRHUjRKaQleg=,iv:0Ra5+u4KFX1BGTdbRWOHgQ7XUYy7q5/ACEScPB9s+PE=,tag:p+1UOuFqYq11Lj/EdH8o1Q==,type:str]
    #ENC[AES256_GCM,data:z3IQ6bjL0v3f8xqYaXcRZbQYKdyXBSr+IOy97OpAXOHR3tFEdJZ41gTyr+azOyB3phMes3N6LmoenoIGf4sXvxHSCIeVySN3gHBQ+uFyVDze,iv:UcDQCuIOjH+bknZCmk3GdEIQz8jyl8p+ErTJv2QxJzQ=,tag:y0IZkv5G4Q7uB3vLygl+zQ==,type:comment]
    #ENC[AES256_GCM,data:d9wWwGRx7XzKvsFMIt+2/ilRDvF3ah2y+n68srWnWcp2/FCdjNFix111cvo5JUvrIABJq40KR/Ncum1+UFlwNsFTKzR6C4OJIbn1wuo=,iv:5iobbM6BU27faCY0wYNqY7SpvaCLbr+gc7GC3YmQDnE=,tag:5JQlhU19L6WgRL9djQ3oSg==,type:comment]
    AUTH_COGNITO_SECRET: ENC[AES256_GCM,data:QR1tzHO9Sx08kc5H1/osC2wdW9f40qp7flZ6f2NCrrWCL/XfW7cReoN53dAh4vstcTdp,iv:yno+0VCId4AguxAotbwVU+jNg3EAcq6QKCBpFWHZNsI=,tag:eKytg3QzpGDX3d//LwS3Kg==,type:str]
sops:
    age:
        - recipient: age14ywlc408mw4w063s097prew9kkq5mphk82a9yvx6l4f0uu8ljusq4c2zmq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT0lYZTBrVCs2aWhuZUhQ
            QXlFOGEwMEVVSXVWNUdPS0lqMXFMQ0wxUEJZClZZZVU3QVN2ZTdLOE4yYVptUmRl
            Z2tBMlpINURteXBiNE8wVEhyWG5PRGMKLS0tIHVnK1krdHd4ckRIeTRYKzlvQ04v
            WUdJZnNLQjdCUlVOKzJYR1IxVk5McVkKEeKxd0OQBfJxnTS+aYyl+ZmkAgTXl+ch
            gAOG2ZS0GC9SyDi2f0bEgIriI5ixccFG5ZIlnY1UxXLor71jUyt3zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T14:20:37Z"
    mac: ENC[AES256_GCM,data:ZWmq/Du4654cvETPtlZrC8CLDE8kxQ1k8niUm7Lyt/nHCu1ijfz608Q0HzIj55pMoOY9ELpMofavn93mk8rYFdWDGE0bA3HHzntIXvpC+aNRhJfgqEygVdlOQvZ9SXBdGZHVstyU9iH067x1prw90eO+ZT5w75ejEz3N0btjk+U=,iv:MZYbQD6UETuGsSKmVWkx8VmIhtFyCIVxHWk8FqFntns=,tag:eBj3mtopjZupHTnXYp6ASA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
